backend = "glx";

shadow = true;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = true;

fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;
no-fading-destroyed-argb = true;

#corner-radius = 10;

rounded-corners-exclude = [
    "class_g = 'Polybar'"
]
