plugins: musicbrainz edit scrub embedart missing info fetchart lyrics lastgenre
import:
  move: yes
  language: en
  from_scratch: yes
embedart:
  auto: no
  clearart_on_import: yes
fetchart:
  auto: yes
scrub:
  auto: no
lyrics:
  auto: yes
  synced: yes
lastgenre:
  auto: yes
