# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$username$status$container$directory>> '

[directory]
truncate_to_repo = false
truncation_symbol = ".../"
home_symbol = '$HOME'
style = 'bold yellow'

[container]
style = 'dimmed yellow'
format = '[\[$name\] ]($style)'
