#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#
# Launch the environment
# TODO: Make this a script
#

# Update ENV vars
# We need this for the Polybar scripts to function
export PATH=$HOME/scripts:$HOME/usr/local/bin:$HOME/bin:$PATH

# Set the BG
feh --bg-fill --no-fehbg /home/callum/Pictures/wallpapers/bici.jpg

#
# Workspace Setup
#

bspc monitor -d 1 2 3 4 5 6 7 8 9

#
# Display Setup
#

# Increase polling rate for pointer to suit 170Hz
bspc config pointer_motion_interval 12

#
# Gaps Setup
#

bspc config border_width          2
bspc config focused_border_color  '#ffffff'
bspc config window_gap            4

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer false


#
# Window Rules
#

bspc rule -a 'Gimp-2.10' desktop='^5' focus=off follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Minecraft Launcher' state=floating follow=off
bspc rule -a Nemo state=floating
bspc rule -a discord desktop='^3' follow=off focus=off
bspc rule -a firefox desktop='^2' follow=on

# X Settings
xinput --set-prop 8 307 0, 1
xinput --set-prop 8 308 0, 1
xsetroot -cursor_name left_ptr


# Cleanup running polybar instances
already_running_inst=$(pgrep 'polybar')
for polybar_inst in $already_running_inst
do
  kill "$polybar_inst"
done

picom -c --experimental-backends --use-ewmh-active-win --backend glx --glx-no-stencil --glx-no-rebind-pixmap  --xrender-sync-fence &

polybar &

