;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
base = #1e1e2e
mantle = #181825
crust = #11111b

text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de

surface0 = #313244
surface1 = #45475a
surface2 = #585b70

overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2


blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc

transparent = #FF00000

[bar/main]

override-redirect = false

width = 100%
height = 38pt

background = ${colors.base}
foreground = ${colors.text}

line-size = 3pt

padding = 2
padding-left = 0
padding-right = 1

module-margin = 1

font-0 = FuraMono Nerd Font; 2
font-1 = Noto Sans Symbols2

modules-left = xworkspaces
modules-right = dark_mode pulseaudio date
modules-center = music

cursor-click = pointer
cursor-scroll = ns-resize

;tray-position = left

enable-ipc = true

; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.overlay1}
label-active-underline= ${colors.rosewater}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.surface1}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.surface1}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-underline = ${colors.rosewater}
format-volume = <label-volume>
label-volume = 墳 %percentage%%

format-muted-underline = ${colors.rosewater}
format-muted = <label-muted>
label-muted = ﱝ  --
label-muted-foreground = ${colors.surface1}

[module/date]
type = internal/date
interval = 1

date =  %I:%M %p
date-alt =  %d-%m-%Y

label = %date%
label-underline = ${colors.rosewater}

[module/power]
type = custom/text

content = ⏻
content-foreground = ${colors.red}
content-padding = 1pt

click-left = ~/.config/rofi/powermenu/type-1/powermenu.sh
click-right = powermenu_t1

[module/music]
type = custom/script

exec = get_curr_song
label = %output%
label-underline = ${colors.mauve}

interval = 1

[module/dark_mode]
type = custom/text
content = 望
content-foreground = ${colors.blue}
content-padding = 2pt
content-underline = ${colors.rosewater}

click-left = dark_mode_enabled.sh true
click-right = dark_mode_enabled.sh false

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

[module/powermenu]
type = custom/menu
menu-0-0 = Poweroff
menu-0-0-exec = echo hi
menu-0-1 = Suspend
menu-0-1-exec = echo hi

